### ISSUE TITLE
multiple handsontable is not supported in a single page due to getElementsByClassName

### ISSUE THREAD

**Issue by ebengtso** [asselinpaul/medium-editor-handsontable#2]
cannot have a standalone handsontable and medium-text-handsontable in the same page due to getElementsByClassName inside the parse method.

Solution:

```
function parse() {
    var spreadsheets = document.getElementsByClassName('medium-text-handsontable');
```

and added className in draw:

```
function draw(container, data, contextMenuBool, readOnlyBool) {
    var html = new Handsontable(container, {
        data: data,
        className: "medium-text-handsontable",
```

**Comment by asselinpaul** [comment]
Fixed in https://github.com/asselinpaul/medium-editor-handsontable/commit/f728180c5ca661338211727e19c9a622df81e430 !
